# Fine-tuning 

model:
  # model name
  name: "mistralai/Mistral-7B-Instruct-v0.2"
  # Uncomment the following line to use a different model
  # name: "ibm/merlinite-7b"

# optimizer settings
optimizer:
  name: AdamW
  initial_lr: 2e-5
  lr_schedule:
    type: cosine_decay
    warmup_steps: 10
  betas: [0.9, 0.95]
  eps: 1e-5
  weight_decay: 0.1

# checkpointing
checkpoint:
  frequency: 500
  output_dir: './output/calvin/checkpoints'

# training
training:
  num_epochs: 1
  total_iterations: 2000

# batches
batch:
  output_dir: './output/calvin/batches'
  file_prefix: 'calvin'