model:
  name: "lazyfox"

optimizer:
  name: "AdamW"
  initial_lr: 0.01
  lr_schedule:
    type: cosine_decay
    warmup_steps: 10
  betas: [0.9, 0.95]
  eps: 1e-5
  weight_decay: 0.1

checkpoint:
  output_dir: "./output/lazyfox/checkpoints"
  frequency: 50

training:
  num_epochs: 50
  total_iterations: 5000
  loss_function: models.architectures.lazyfox.lazyfox_loss_function.chukloss

batch:
  output_dir: "./output/lazyfox/batches"
  file_prefix: "lazyfox"
